### ISSUE TITLE
Version 2.0.0

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/lumio#1]
A backlog for the [Version 2.0.0](https://github.com/arcticicestudio/lumio/milestone/1) milestone.
The whole project should be rewritten and cleaned up to adapt to the new project setup like the [Nord](https://github.com/arcticicestudio/nord) project.

## Sub-Issues
All sub-issues are listed below and will be merged into the main milestone branch [`release/ghi-#1-2.0.0`](https://github.com/arcticicestudio/lumio/tree/release/ghi-%231-2.0.0).

  - [x] #2  Adapt new project setup and documentation style
  - [x] #3  Rewrite Sass sources
  - [x] #4  Rewrite LESSCSS sources
  - [x] #5 Recreate native sources
  - [x] #6 Travis CI and Circle CI build integration
  - [x] #7  NPM
  - [x] #8  Gulp

### Naming Scheme
**Color names**
The current naming scheme, where each color got an individual name based on the value, will be replaced with an numbered format.
Example: `dark-livid-wood` will be renamed to `lumio0`, `sandrift` to `lumio17`.
This will continue with a continuous numerating where the current position of a color represents its number.

**Components**
Next to this, the color palette will be divided into fifteen named components to represent the different color effects where each component contains a different amount of colors:  
  1. **Rough Coal** `lumio0` - `lumio4`  
  2. **Soft Earth** `lumio5` - `lumio13`  
  3. **Hard Metal** `lumio14` - `lumio17`  
  4. **Piquant Olive** `lumio18` - `lumio21`
  5. **Cold Snow** `lumio22` - `lumio25`
  6. **Clear Water** `lumio26` - `lumio34`
  7. **Hot Flame** `lumio35` - `lumio40`
  8. **Roasted Cocoa Bean** `lumio41` - `lumio46`
  9. **Tropical Wood** `lumio47` - `lumio51`
  10. **Fine Sand** `lumio52` - `lumio56`
  11. **Sweet Banana** `lumio57` - `lumio60`
  12. **Calm Sunset** `lumio61` - `lumio65`
  13. **Living Forest** `lumio66` - `lumio70`
  14. **Deep Sea** `lumio71` - `lumio75`
  15. **Fresh Wild Berries** `lumio76` - `lumio80`

The X11 color scheme names and RGB value variables will be removed, but X11 color names will be included in the Sass- and LESSCSS source documentations.

### Source Formats
**Sass**
All [Sass](http://sass-lang.com)  sources will be documented via [SassDoc](http://sassdoc.com) and a `template-css.scss` will be available to compile a CSS file with all color variables which is cimpatible to the CSS specification.
The SassDoc will be configurable via the `.sassdocrc` file.

**LESSCSS**
All [LESSCSS](http://lesscss.org) sources will be documented via [KSS](http://warpspire.com/kss).

**Native**
All native files will be recreated containing the new color and new color naming scheme.

### Build Tools
**Gulp**
Introduce a [Gulp](gulpjs.com) file to compile Sass sources to CSS, provide a local live-server by watching the filesystem for changes and build the new [SassDoc](http://sassdoc.com).
This will result in the following NPM `devDependencies` with the current versions:  

``` json
    "del": "2.2.2",
    "gulp": "3.9.1",
    "gulp-help": "1.6.1",
    "gulp-plumber": "1.1.0",
    "gulp-rename": "1.2.2",
    "gulp-sass": "2.3.2",
    "gulp-util": "3.0.7",
    "sassdoc": "2.1.20",
    "sassdoc-theme-flippant": "0.1.0"
```

**Travis CI and Circle CI**
Add `.travis.yml` and `circle.yml` configuration files for continous integration web services.

### NPM
A `package.json` file will be added to provide project meta data and dependencies for a release as a Node.js package.

### Assets
All project branding assets will be removed and replaced with the new, modern SVG and AI files.

### Documentations
All project documentations will be rewritten like the `README.md`, `CHANGELOG.md` and `LICENSE.md`.
The project license for the code will be changed to the Apache 2.0 license.

### Git
The `.gitignore` and `.gitattributes` files will be rewritten to remove the high amount of unused pattern and doccomments.
