### ISSUE TITLE
Adapt new project setup and documentation style

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/lumio#2]
**Tasks**
  - [x] Refactor the `.gitignore` and `.gitattributes` files
  - [x] Delete old project files
  - [x] Update the `README.md` and `CHANGELOG.md` files to the new documentation style
  - [x] Move to the Apache 2.0 license
  - [x] Add the new project branding assets

Detailed information can be found in the milestone backlog issue #1.
