### ISSUE TITLE
Rewrite Sass sources

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/lumio#3]
### Tasks
  - [x] Rename all variables to the new naming scheme
  - [x] Write SassDoc
  - [x] Create SassDoc configuration dotfile `.sassdocrc`
  - [x] Implement the `template-css.scss` file

Detailed information can be found in the milestone backlog issue #1.
