### ISSUE TITLE
Recreate native format sources

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/lumio#5]
**Tasks**
  - [x] Create "Adobe Photoshop Color Palette" file
  - [x] Create "Adobe Swatch Exchange" file
  - [x] Create "Gpick Palette" file 
  - [x] Create "GIMP/Inkscape/CinePaint/Krita Palette" file
  - [x] Create "Alias/WaveFront Material" file

Detailed information can be found in the milestone backlog issue #1.
