### ISSUE TITLE
Gulp

### ISSUE THREAD

**Issue by arcticicestudio** [arcticicestudio/lumio#8]
:grey_exclamation: This feature depends on the NPM `package.json` file and must be implemented after #7 :grey_exclamation: 

**Tasks**
  - [x] Implement the [gulpfile](http://gulpjs.com)
    - [x] Implement `clean` task
    - [x] Implement `clean-css` task
    - [x] Implement `clean-documentation` task
    - [x] Implement `compile-css-template` task
    - [x] Implement `default` task which calls the `help` plugin
    - [x] Implement `sassdoc` task

Detailed information can be found in the milestone backlog issue #1.
